/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'CustomAppIcons';
  static const String? _kFontPkg = null;

  static const IconData camera_flip = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ham_menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_filled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror_outline = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_off = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_on = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
